"""Create user, garment, context tables

Revision ID: ddacbbcecc45
Revises: bb03f7ebc693
Create Date: 2025-11-12 14:30:06.783277

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ddacbbcecc45'
down_revision = 'bb03f7ebc693'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('context',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('season', sa.String(length=50), nullable=True),
    sa.Column('weather_condition', sa.String(length=50), nullable=True),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.Column('activity', sa.String(length=50), nullable=True),
    sa.Column('mood', sa.String(length=50), nullable=True),
    sa.Column('formality_level', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('garment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('primary_color', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('pattern', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('material', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('formality_level', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('type_group', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('image_url', sa.String(length=255), nullable=True))
        batch_op.drop_column('color')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('age', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('body_shape', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('style_preference', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('skin_tone', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('gender', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('gender')
        batch_op.drop_column('skin_tone')
        batch_op.drop_column('style_preference')
        batch_op.drop_column('body_shape')
        batch_op.drop_column('age')

    with op.batch_alter_table('garment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('color', mysql.VARCHAR(length=50), nullable=False))
        batch_op.drop_column('image_url')
        batch_op.drop_column('type_group')
        batch_op.drop_column('description')
        batch_op.drop_column('formality_level')
        batch_op.drop_column('material')
        batch_op.drop_column('pattern')
        batch_op.drop_column('primary_color')

    op.drop_table('context')
    # ### end Alembic commands ###
